menu:
  Home: /
  Archives: /archives
  Resume: /resume

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

facebook:
google_plus:
twitter:
github:

fancybox: true
google_analytics:
rss:
